### ISSUE TITLE
One tool, one container

### ISSUE THREAD

**Issue by mr-c** [ypriverol/containers-rules-manuscript#7]
For maximum reusability and smaller containers.

**Comment by ypriverol** [comment]
100% agree with this rule. I think, it should be the first rule of the guidelines/manuscript. I will refelct this into the paper an in the BioContainers specification. Are you agree @prvst ?

**Comment by prvst** [comment]
did we came to a different conclusion at some point during the development of our project ? I thought that we decided this on the beginning. Just have in mind that although that's our goal with the containers, there will be cases where more than one tool will be necessary, like DIA-Umpire. I don't think we should exclude these cases, we can just tag them as _pipelines_ or _complex_

**Comment by ypriverol** [comment]
Is difficult to define, what is a `one tool`. Especially, because this depends on the way the tool has been developed originally. For example, if `DIA-UMPIRE` contains multiple tools, executable, it is difficult to **BioContainers** to realize that this is a multiple tools. However, we should care about do not encapsulate more than one tool into the container, lets said `tools from different providers in the same container`. We have been following that rule in biocontainers/bioconda but would be good to make the statement. @mr-c do you know a place we can find a more formal definition of what is a `one tool`.

**Comment by osallou** [comment]
I do not fully agreee with "tools from different providers in the same container" term.
Some tools execute other tools (tool A needs tools B and C to work). So in this case, we have tools from different sources/providers in a single container, because tool A cannot work without tools B and C.

**Comment by ypriverol** [comment]
I understand your point @osallou. However, if tool B and C are used by another tool let said D, then we need to pack B and C again inside D. In principle, we should aim and try to have independent containers for each of these tools. What we should aim and promote here is that tool A, B and C are different containers.

**Comment by osallou** [comment]
A, B and C should exists as different containers, as they all are different tools. But if A **needs** B and C to execute, B and C need to be installed in container A too, else A won't work. See it as dependencies just like for libraries.

**Comment by prvst** [comment]
@osallou has a point here, our definition of "one container, one tool" should be more flexible, maybe it should lean more towards the functional aspect of the software, and not the "physical" side of it.

**Comment by ypriverol** [comment]
Hi all: 
 I have drafted the intro and this first recommendation. Please feel free to contribute and do PR with changes.

**Comment by ypriverol** [comment]
This is already in the draft. I will close this issue.
